version: '3'
services:
  web:
    build:
      context: ./web
    stdin_open: true
    tty: true
    volumes:
      - ./web:/home/app
    ports:
      - 3000:3000
    command: /bin/sh -c "yarn install && yarn start"
  go:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - .:/home/app
    ports:
      - 10330:10330
    depends_on:
      - "db"
    command: /bin/sh -c "go get github.com/cespare/reflex && reflex -r '(\.go|go\.mod)' -s go run main.go"
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: paddle
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 8001:3306

volumes:
  db-data:
    driver: local
