version: '3.8'
services:
  web:
    build:
      context: .
      target: web
    stdin_open: true
    tty: true
    volumes:
      - ./web:/home/node:cached
    ports:
      - 13000:13000
    command: /bin/sh -c "yarn install --network-timeout 1000000 && yarn start"
  go:
    build:
      context: .
      target: app
    stdin_open: true
    tty: true
    volumes:
      - .:/home/app:cached
    ports:
      - 10330:10330
    depends_on:
      - "db"
    command: /bin/sh -c "go get github.com/cespare/reflex && reflex -r '(\.go|go\.mod)' -s go run main.go"
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: paddle
      MYSQL_USER: apuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - 8001:3306

volumes:
  db-data:
    driver: local
