# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  lint:
    docker:
      - image: cimg/node:14.16.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-node-{{ checksum "./web/yarn.lock" }}
      - run:
          name: Execute Lintfix
          command: |
            git branch
            cd web && yarn install
            yarn lintfix
            if [[ -z "$(git status --porcelain)" ]]; then
              git config user.email "chubachi+pt+circleci@users.noreply.github.com"
              git config user.name "chubachi+pt+circleci"
              git add .
              # git commit --allow-empty -m "[skip ci] lintfix"
              # git push
            fi
      - save_cache:
          key: v1-node-{{ checksum "./web/yarn.lock" }}
          paths:
            - ./web/node_modules
      - run:
          name: Execute Lint
          command: |
            yarn lint

  test:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.29.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker-compose build
          command: |
            set -x
            docker-compose build
          no_output_timeout: 20m
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up -d
          no_output_timeout: 20m
      - run:
          name: test
          command: |
            mkdir /tmp/test-results
      - run:
          name: docker-compose stop
          command: |
            set -x
            docker-compose stop
      - run:
          name: docker-compose down
          command: docker-compose down
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  deploy:
    machine: true
    working_directory: ~/repo
    parameters:
      connection_key_fingerprint:
        type: string
      deploy_key_fingerprint:
        type: string
    steps:
      - add_ssh_keys:
          fingerprints:
            - << parameters.connection_key_fingerprint >>
            - << parameters.deploy_key_fingerprint >>
      - run:
          name: Setup Deployment Key
          command: |
            CONNECTION_KEY_FINGERPRINT=<< parameters.connection_key_fingerprint >>
            DEPLOY_KEY_FINGERPRINT=<< parameters.deploy_key_fingerprint >>
            scp -P ${SSH_PORT} -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_${CONNECTION_KEY_FINGERPRINT//:/} ~/.ssh/id_rsa_${DEPLOY_KEY_FINGERPRINT//:/} ${USERNAME}@${HOST}:/home/${USERNAME}/.ssh/id_rsa
      - run:
          name: Package Install
          command: |
            COMPOSE_PATH=/usr/local/bin/docker-compose
            ssh -p ${SSH_PORT} -o StrictHostKeyChecking=no ${USERNAME}@${HOST} \<< EOF
              sudo yum update -y && sudo yum install -y git docker
              if [[ ! -e ${COMPOSE_PATH} ]]; then
                sudo curl -L https://github.com/docker/compose/releases/download/1.29.1/docker-compose-`uname -s`-`uname -m` -o ${COMPOSE_PATH}
                sudo chmod +x ${COMPOSE_PATH}
                # sudo curl -L --fail https://raw.githubusercontent.com/linuxserver/docker-docker-compose/master/run.sh -o ${COMPOSE_PATH}
                # sudo chmod +x /${COMPOSE_PATH}
                sudo ln -s ${COMPOSE_PATH} /usr/bin/docker-compose
              fi
              sudo systemctl start docker && sudo systemctl enable docker
              # 監視ファイル数の上限変更
              echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
              sudo sysctl -p
            EOF
      - run:
          name: Service Deployment
          command: |
            GIT_PATH=/home/${USERNAME}/${CIRCLE_PROJECT_REPONAME}
            ssh -p ${SSH_PORT} -o StrictHostKeyChecking=no ${USERNAME}@${HOST} \<< EOF
              ssh-keyscan github.com > ~/.ssh/known_hosts
              if [[ ! -e ${GIT_PATH} ]]; then
                git clone ${CIRCLE_REPOSITORY_URL}
              fi
              cd ${GIT_PATH} && git checkout main && git pull
              sudo docker-compose stop && sudo docker-compose up -d
            EOF

workflows:
  test:
    jobs:
      - lint:
          filters:
            branches:
              ignore:
                - main
      - test:
          filters:
            branches:
              ignore:
                - main
  test-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main
          connection_key_fingerprint: 3b:67:c0:14:65:66:df:39:ac:ac:a8:e7:d9:73:d0:9c
          deploy_key_fingerprint: aa:04:58:74:f8:7b:56:f4:47:47:cb:42:ab:70:2a:c8
